# This is a basic workflow to help you get started with Actions

name: Getting Started - Tapas

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: step 1 - checkout the main Github branch
        uses: actions/checkout@v3      
      - name: Run a one-line script
        run: echo Hello, world!      
      - name: Run a multi-line script
        run: |
          echo Nothing to see in multiline script
          sh ./github-actions-script.sh
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
      - name: check python version
        run: python --version
        
        
      
      
          
          
